---
platform: linux
image_resource:
  type: docker-image
  source: {repository: boshcpi/cpi-certification}

inputs:
  - name: pipelines
  - name: bats
  - name: director-state

outputs:
  - name: bats-config

run:
  path: pipelines/softlayer/tasks/prepare-bats.sh

params:
  STEMCELL_NAME:          ""
  BAT_VCAP_PASSWORD:      ""
  BOSH_DIRECTOR_USER:     ""
  BOSH_PASSWORD:          ""