---
platform: linux
image_resource:
  type: docker-image
  source: {repository: boshcpi/cpi-certification}

inputs:
  - name: pipelines
  - name: bosh-release
  - name: cpi-release
  - name: stemcell

outputs:
  - name: director-config

run:
  path: pipelines/softlayer/tasks/prepare-director.sh

params:
  BOSH_CLIENT:               ""
  BOSH_CLIENT_SECRET:               ""
  SL_VM_NAME_PREFIX:                    ""
  SL_VM_DOMAIN:                         ""
  SL_DATACENTER:                        ""
  SL_VLAN_PUBLIC:                       ""
  SL_VLAN_PRIVATE:                      ""
  SL_USERNAME:                          ""
  SL_API_KEY:                           ""
  USE_REDIS:                            ""